export const merchantFilter = [
    { id: 'geography', label: 'Geography', subOptions: ['North', 'East', 'West', 'South'] },
    { id: 'type-of-merchant', label: 'Merchant Type', subOptions: ['Agricultural Products', 'Livestock Products'] },
    { id: 'business-size', label: 'Business Size', subOptions: ['Small (< 50 Lakhs)', 'Medium ( 50 Lakhs - 1 Crore)','Large (> 1 crore)'] },
    { id: 'primary-goods-traded', label: 'Primary Goods Traded', subOptions: ['Non-Perishable Goods', 'Perishable Goods'] },
    { id: 'use-of-technology', label: 'Use of Technology', subOptions: ['Digitally Integrated', 'Traditionally Operated'] },
    // { id: 'annual-revenue', label: 'Annual Revenue', subOptions: ['Less than ₹50,00,000', 'More than ₹50,00,000'] },
    { id: 'loan-amount-required', label: 'Loan Amount Required', subOptions: ['Less than ₹50,00,000', 'More than ₹50,00,000'] },
  ];
  

export const tempMerchantProfile = [
    {
      id: 1,
      name: "Aniket",
      state: "Punjab",
      "Amount Required": 100000,
      "Annual Revenue": 1500000,
      amountReceived: 100000,
      "PRIMARY GOODS TRADED": "Cotton, Sugarcane",
      EXPERIENCE: "Not specified",
      "CREDIT SCORE": "680 (B)",
      "MARKET ACCESS": "Good; established local market presence The merchant has solid connections within the local market, ensuring a consistent demand for his traded goods.",
      "TECHNOLOGY USE": "Traditional; relies on conventional trading methods  Utilizes basic, traditional methods for trading and inventory management, with potential benefits from adopting modern technologies.",
      "SUSTAINABILITY PRACTICES": "Basic; limited implementation of sustainable practices (C) Currently, sustainability practices are minimal, focusing more on traditional farming and trading methods.",
      "FINANCIAL HEALTH": "Moderate; stable annual revenue with room for growth (B) Financially stable with an annual revenue of ₹45,00,000, but the business could benefit from expansion and efficiency improvements",
      "RISK FACTORS": "Moderate market risk due to dependency on crop yields and price fluctuations (C+) Exposure to market volatility based on crop yields and pricing, with potential impacts from adverse weather conditions and market demand.",
      "LOAN AMOUNT RECOMMENDED": "₹1,10,000",
      REPAYMENT_STRUCTURE: "Monthly installments over 3 years with seasonal adjustments  Taking into account the seasonal nature of cash crop trading, repayment should accommodate fluctuating income streams.",
      "Overall Rating": "B+",
      Recommendation: "Amit Verma is eligible for a ₹1,10,000 loan with a structured monthly repayment plan that considers seasonal income variations. Suggested investments include modernizing inventory management systems and enhancing supply chain operations to increase efficiency and reduce market risks. Additionally, adopting more sustainable practices could improve long-term viability and market appeal.",
      "North India": true,
      "South India": false,
      "East India": false,
      "West India": false,
      "Agricultural Products": false,
      "Livestock Products": true,
      "Small (< 50 Lakhs)": false,
      "Medium ( 50 Lakhs - 1 Crore)": true,
      "Large (> 1 crore)":false,
      "Non-Perishable Goods": false,
      "Perishable Goods": true,
      "Modern (E-commerce, ONDC Platform, Digital Payments)": false,
      Traditional: true,
      "Less than ₹50,00,000": true,
      "More than ₹50,00,000": false,
      "Less than ₹1,00,000": false,
      "More than ₹1,00,000": true,

    //   ------------------------------
        
    
        "Name": "Priya Menon",
        "Location": "Chennai, Tamil Nadu, South India",
        "Business Type": "Food Grains & Livestock Products",
        "Business Size": "Large",
        "Primary Goods Traded": "Non-Perishable Goods (Grains, Lentils)",
        "Experience": 12,
        "Data Sets Used": {
          "Banking Data": "Account activity and transaction history, Loan repayment records",
          "Bureau Data": "Credit score and credit history, Outstanding debts and repayment behavior",
          "Telecom and Utility Data": "Mobile phone usage and payment patterns, Timeliness and consistency of utility bill payments",
          "GST Data": "Sales and purchase records, Tax filing history and compliance",
          "ONDC Data": "Transaction volume and history"
        },
        "Validations": {
          "GST Registration": "Yes",
          "Borrower Identity": "Yes"
        },
        "Business Health Report": {
          "Technical Assessment": {
            "Inventory Levels": "High",
            "Revenue Trends": "Positive and growing",
            "Customer Base": "Expanding",
            "Image": "(Image of the business premises can be included here)"
          },
          "Assessment Summary": {
            "Credit Score": 750,
            "Market Access": "Excellent; well-established relationships with national buyers and retailers (A)",
            "Technology Use": "High; utilizes modern e-commerce platforms and digital payment systems (A)",
            "GST Data": "Excellent; consistent sales and purchase records with full compliance (A)",
            "Financial Health": "Strong; robust revenue with diversified trading partnerships (A)",
            "Risk Factors": "Low market risk due to high demand for non-perishable goods (B)"
          },
          "Overall Rating": "A",
          "Recommendation": "Priya Menon is eligible for a loan. Suggested investments in expanding inventory and enhancing digital marketing strategies to increase market reach and revenue."
        },
    },
    
    {
      id: 2,
      name: "Suresh",
      state: "Gujarat",
      "Amount Required": 150000,
      "Annual Revenue": 2000000,
      amountReceived: 120000,
      "PRIMARY GOODS TRADED": "Wheat, Rice",
      EXPERIENCE: "More than 5 years",
      "CREDIT SCORE": "720 (A)",
      "MARKET ACCESS": "Excellent; strong network and established reputation",
      "TECHNOLOGY USE": "Modern; leverages digital platforms for trading and sales",
      "SUSTAINABILITY PRACTICES": "Advanced; implements innovative sustainable practices for farming and trading",
      "FINANCIAL HEALTH": "Healthy; consistent growth in revenue and profitability",
      "RISK FACTORS": "Low; diversified income sources and stable market demand",
      "LOAN AMOUNT RECOMMENDED": "₹1,50,000",
      REPAYMENT_STRUCTURE: "Quarterly installments over 5 years with flexible options for early repayment",
      "Overall Rating": "A+",
      Recommendation: "Suresh qualifies for a ₹1,50,000 loan with flexible repayment options. He has a strong market presence and utilizes modern technology, with potential for further growth through investment in new markets and sustainable practices.",
      "North India": false,
      "South India": true,
      "East India": false,
      "West India": true,
      "Agricultural Products": true,
      "Livestock Products": false,
      "Small (< 50 Lakhs)": false,
      "Medium ( 50 Lakhs - 1 Crore)": true,
      "Large (> 1 crore)":false,
      "Non-Perishable Goods": true,
      "Perishable Goods": false,
      "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
      Traditional: false,
      "Less than ₹50,00,000": false,
      "More than ₹50,00,000": true,
      "Less than ₹1,00,000": false,
      "More than ₹1,00,000": true,

    //   ------------------------
    
    "Name": "Amit Verma",
    "Location": "Ludhiana, Punjab, North India",
    "Business Type": "Agricultural Products",
    "Business Size": "Small/Medium",
    "Primary Goods Traded": "Cash Crops (Cotton, Sugarcane)",
    "Experience": 8,
    "Data Sets Used": {
      "Banking Data": "Account activity and transaction history, Loan repayment records",
      "Bureau Data": "Credit score and credit history, Outstanding debts and repayment behavior",
      "Telecom and Utility Data": "Mobile phone usage and payment patterns, Timeliness and consistency of utility bill payments",
      "GST Data": "Sales and purchase records, Tax filing history and compliance",
      "ONDC Data": "Transaction volume and history"
    },
    "Validations": {
      "GST Registration": "Yes",
      "Borrower Identity": "Yes"
    },
    "Business Health Report": {
      "Technical Assessment": {
        "Inventory Levels": "Moderate",
        "Revenue Trends": "Stable",
        "Customer Base": "Established",
        "Image": "(Image of the business premises can be included here)"
      },
      "Assessment Summary": {
        "Credit Score": 720,
        "Market Access": "Good; established relationships with local buyers (B)",
        "Technology Use": "Moderate; uses digital payment systems (B)",
        "GST Data": "Good; consistent sales and purchase records (B)",
        "Financial Health": "Stable; consistent revenue with focused trading partnerships (B)",
        "Risk Factors": "Moderate market risk due to price fluctuations in cash crops (C)"
      },
      "Overall Rating": "B",
      "Recommendation": "Amit Verma is eligible for a loan. Suggested investments in inventory expansion and digital marketing to stabilize revenue and reduce market risk."
    },
    }, 
      {
      id: 3,
      name: "Rajesh",
      state: "Maharashtra",
      "Amount Required": 80000,
      "Annual Revenue": 1000000,
      amountReceived: 70000,
      "PRIMARY GOODS TRADED": "Vegetables, Fruits",
      EXPERIENCE: "2-5 years",
      "CREDIT SCORE": "650 (C)",
      "MARKET ACCESS": "Average; some local market presence",
      "TECHNOLOGY USE": "Limited; minimal use of digital platforms",
      "SUSTAINABILITY PRACTICES": "Basic; occasional implementation of sustainable farming methods",
      "FINANCIAL HEALTH": "Stagnant; revenue fluctuates with seasonal demand",
      "RISK FACTORS": "High; dependent on local market conditions and weather",
      "LOAN AMOUNT RECOMMENDED": "₹80,000",
      REPAYMENT_STRUCTURE: "Bi-monthly installments over 2 years with additional payments during peak seasons",
      "Overall Rating": "C-",
      Recommendation: "Rajesh qualifies for an ₹80,000 loan with a repayment plan tailored to his seasonal revenue fluctuations. He could benefit from improving market access and adopting more sustainable farming practices.",
      "North India": false,
      "South India": false,
      "East India": true,
      "West India": false,
      "Agricultural Products": false,
      "Livestock Products": true,
      "Small (< 50 Lakhs)": true,
      "Medium ( 50 Lakhs - 1 Crore)": false,
      "Large (> 1 crore)": false,
      "Non-Perishable Goods": false,
      "Perishable Goods": true,
      "Modern (E-commerce, ONDC Platform, Digital Payments)": false,
      Traditional: true,
      "Less than ₹50,00,000": true,
      "More than ₹50,00,000": false,
      "Less than ₹1,00,000": true,
      "More than ₹1,00,000": false,

        // -----------------------------

        
            "Name": "Vikram Singh",
            "Location": "Patna, Bihar, East India",
            "Business Type": "Agricultural Products",
            "Business Size": "Large",
            "Primary Goods Traded": "Cash Crops (Oilseeds, Tobacco)",
            "Experience": 10,
            "Data Sets Used": {
              "Banking Data": "Account activity and transaction history, Loan repayment records",
              "Bureau Data": "Credit score and credit history, Outstanding debts and repayment behavior",
              "Telecom and Utility Data": "Mobile phone usage and payment patterns, Timeliness and consistency of utility bill payments",
              "GST Data": "Sales and purchase records, Tax filing history and compliance",
              "ONDC Data": "Transaction volume and history"
            },
            "Validations": {
              "GST Registration": "Yes",
              "Borrower Identity": "Yes"
            },
            "Business Health Report": {
              "Technical Assessment": {
                "Inventory Levels": "High",
                "Revenue Trends": "Positive and growing",
                "Customer Base": "Expanding",
                "Image": "(Image of the business premises can be included here)"
              },
              "Assessment Summary": {
                "Credit Score": 740,
                "Market Access": "Excellent; well-established relationships with national buyers and exporters (A)",
                "Technology Use": "High; utilizes ONDC platform and digital payment systems (A)",
                "GST Data": "Excellent; consistent sales and purchase records with full compliance (A)",
                "Financial Health": "Strong; robust revenue with diversified trading partnerships (A)",
                "Risk Factors": "Moderate market risk due to price volatility in cash crops (C)"
              },
              "Overall Rating": "A-",
              "Recommendation": "Vikram Singh is eligible for a loan. Suggested investments in advanced market analysis tools and expanded inventory to mitigate price volatility risks."
            }
        },
    {
      id: 4,
      name: "Priya",
      state: "Tamil Nadu",
      "Amount Required": 120000,
      "Annual Revenue": 1800000,
      amountReceived: 100000,
      "PRIMARY GOODS TRADED": "Rice, Pulses",
      EXPERIENCE: "More than 5 years",
      "CREDIT SCORE": "720 (A)",
      "MARKET ACCESS": "Excellent; strong network and established reputation",
      "TECHNOLOGY USE": "Modern; leverages digital platforms for trading and sales",
      "SUSTAINABILITY PRACTICES": "Advanced; implements innovative sustainable practices for farming and trading",
      "FINANCIAL HEALTH": "Healthy; consistent growth in revenue and profitability",
      "RISK FACTORS": "Low; diversified income sources and stable market demand",
      "LOAN AMOUNT RECOMMENDED": "₹1,20,000",
      REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
      "Overall Rating": "A+",
      Recommendation: "Priya qualifies for a ₹1,20,000 loan with flexible repayment options. She has a strong market presence and utilizes modern technology, with potential for further growth through investment in new markets and sustainable practices.",
      "North India": false,
      "South India": true,
      "East India": false,
      "West India": false,
      "Agricultural Products": false,
      "Livestock Products": true,
      "Small (< 50 Lakhs)": false,
      "Medium ( 50 Lakhs - 1 Crore)": true,
      "Large (> 1 crore)":false,
      "Non-Perishable Goods": true,
      "Perishable Goods": false,
      "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
      Traditional: false,
      "Less than ₹50,00,000": false,
      "More than ₹50,00,000": true,
      "Less than ₹1,00,000": false,
      "More than ₹1,00,000": true,

// ---------------------------------------

        "Name": "Ayesha Khan",
        "Location": "Mumbai, Maharashtra, West India",
        "Business Type": "Food Grains & Livestock Products",
        "Business Size": "Small/Medium",
        "Primary Goods Traded": "Non-Perishable Goods (Dry Fruits, Grains)",
        "Experience": 7,
        "Data Sets Used": {
        "Banking Data": "Account activity and transaction history, Loan repayment records",
        "Bureau Data": "Credit score and credit history, Outstanding debts and repayment behavior",
        "Telecom and Utility Data": "Mobile phone usage and payment patterns, Timeliness and consistency of utility bill payments",
        "GST Data": "Sales and purchase records, Tax filing history and compliance",
        "ONDC Data": "Transaction volume and history"
        },
        "Validations": {
        "GST Registration": "Yes",
        "Borrower Identity": "Yes"
        },
        "Business Health Report": {
        "Technical Assessment": {
            "Inventory Levels": "Moderate",
            "Revenue Trends": "Stable",
            "Customer Base": "Established",
            "Image": "(Image of the business premises can be included here)"
        },
        "Assessment Summary": {
            "Credit Score": 715,
            "Market Access": "Good; established relationships with local retailers (B)",
            "Technology Use": "Moderate; uses e-commerce platforms (B)",
            "GST Data": "Good; consistent sales and purchase records (B)",
            "Financial Health": "Stable; consistent revenue with focused trading partnerships (B)",
            "Risk Factors": "Low market risk due to high demand for non-perishable goods (B)"
        },
        "Overall Rating": "B",
        "Recommendation": "Ayesha Khan is eligible for a loan. Suggested investments in inventory expansion and digital marketing to enhance market reach and revenue stability."
        }
    },
    
    {
      id: 5,
      name: "Kiran",
      state: "Karnataka",
      "Amount Required": 90000,
      "Annual Revenue": 1200000,
      amountReceived: 80000,
      "PRIMARY GOODS TRADED": "Maize, Millets",
      EXPERIENCE: "2-5 years",
      "CREDIT SCORE": "670 (B-)",
      "MARKET ACCESS": "Average; moderate connections in local market",
      "TECHNOLOGY USE": "Basic; limited use of digital platforms",
      "SUSTAINABILITY PRACTICES": "Intermediate; implements some sustainable farming methods",
      "FINANCIAL HEALTH": "Stable; consistent revenue with potential for growth",
      "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
      "LOAN AMOUNT RECOMMENDED": "₹90,000",
      REPAYMENT_STRUCTURE: "Quarterly installments over 3 years with adjustments during peak seasons",
      "Overall Rating": "B",
      Recommendation: "Kiran qualifies for a ₹90,000 loan with a repayment plan designed to accommodate seasonal variations. Further investment in technology and sustainable practices could enhance profitability and reduce risk.",
      "North India": false,
      "South India": true,
      "East India": false,
      "West India": false,
      "Agricultural Products": true,
      "Livestock Products": false,
      "Small (< 50 Lakhs)": true,
      "Medium ( 50 Lakhs - 1 Crore)": false,
      "Large (> 1 crore)": false,
      "Non-Perishable Goods": false,
      "Perishable Goods": true,
      "Modern (E-commerce, ONDC Platform, Digital Payments)": false,
      Traditional: true,
      "Less than ₹50,00,000": true,
      "More than ₹50,00,000": false,
      "Less than ₹1,00,000": true,
      "More than ₹1,00,000": false,


    //   -----------------

    "Name": "Rahul Desai",
    "Location": "Gurgaon, Haryana, North India",
    "Business Type": "Agricultural Products",
    "Business Size": "Small/Medium",
    "Primary Goods Traded": "Cash Crops (Cotton, Jute)",
    "Experience": 9,
    "Data Sets Used": {
      "Banking Data": "Account activity and transaction history, Loan repayment records",
      "Bureau Data": "Credit score and credit history, Outstanding debts and repayment behavior",
      "Telecom and Utility Data": "Mobile phone usage and payment patterns, Timeliness and consistency of utility bill payments",
      "GST Data": "Sales and purchase records, Tax filing history and compliance",
      "ONDC Data": "Transaction volume and history"
    },
    "Validations": {
      "GST Registration": "Yes",
      "Borrower Identity": "Yes"
    },
    "Business Health Report": {
      "Technical Assessment": {
        "Inventory Levels": "Moderate",
        "Revenue Trends": "Stable",
        "Customer Base": "Established",
        "Image": "(Image of the business premises can be included here)"
      },
      "Assessment Summary": {
        "Credit Score": 725,
        "Market Access": "Good; established relationships with local textile mills (B)",
        "Technology Use": "Moderate; uses digital payment systems (B)",
        "GST Data": "Good; consistent sales and purchase records (B)",
        "Financial Health": "Stable; consistent revenue with focused trading partnerships (B)",
        "Risk Factors": "Moderate market risk due to price volatility in cash crops (C)"
      },
      "Overall Rating": "B",
      "Recommendation": "Rahul Desai is eligible for a loan. Suggested investments in inventory expansion and market analysis tools to mitigate price volatility risks."
    }
},
    {
      id: 6,
      name: "Neha",
      state: "Uttar Pradesh",
      "Amount Required": 110000,
      "Annual Revenue": 1600000,
      amountReceived: 100000,
      "PRIMARY GOODS TRADED": "Wheat, Pulses",
      EXPERIENCE: "More than 5 years",
      "CREDIT SCORE": "720 (A+)",
      "MARKET ACCESS": "Excellent; well-established network with strong market presence",
      "TECHNOLOGY USE": "Advanced; utilizes digital platforms for trading and sales",
      "SUSTAINABILITY PRACTICES": "High; actively implements sustainable farming methods",
      "FINANCIAL HEALTH": "Robust; consistent growth in revenue and profitability",
      "RISK FACTORS": "Low; diversified income sources and stable market demand",
      "LOAN AMOUNT RECOMMENDED": "₹1,10,000",
      REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
      "Overall Rating": "A+",
      Recommendation: "Neha qualifies for a ₹1,10,000 loan with flexible repayment options. With strong market access and advanced technology use, she has the potential for significant growth and expansion.",
      "North India": true,
      "South India": false,
      "East India": false,
      "West India": false,
      "Agricultural Products": false,
      "Livestock Products": true,
      "Small (< 50 Lakhs)": false,
      "Medium ( 50 Lakhs - 1 Crore)": true,
      "Large (> 1 crore)":false,
      "Non-Perishable Goods": true,
      "Perishable Goods": false,
      "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
      Traditional: false,
      "Less than ₹50,00,000": false,
      "More than ₹50,00,000": true,
      "Less than ₹1,00,000": false,
      "More than ₹1,00,000": true,

    //   ---------------------------------------

    "Name": "Sunita Reddy",
    "Location": "Bengaluru, Karnataka, South India",
    "Business Type": "Food Grains & Livestock Products",
    "Business Size": "Large",
    "Primary Goods Traded": "Non-Perishable Goods (Grains, Lentils)",
    "Experience": 11,
    "Data Sets Used": {
      "Banking Data": "Account activity and transaction history, Loan repayment records",
      "Bureau Data": "Credit score and credit history, Outstanding debts and repayment behavior",
      "Telecom and Utility Data": "Mobile phone usage and payment patterns, Timeliness and consistency of utility bill payments",
      "GST Data": "Sales and purchase records, Tax filing history and compliance",
      "ONDC Data": "Transaction volume and history"
    },
    "Validations": {
      "GST Registration": "Yes",
      "Borrower Identity": "Yes"
    },
    "Business Health Report": {
      "Technical Assessment": {
        "Inventory Levels": "High",
        "Revenue Trends": "Positive and growing",
        "Customer Base": "Expanding",
        "Image": "(Image of the business premises can be included here)"
      },
      "Assessment Summary": {
        "Credit Score": 740,
        "Market Access": "Excellent; well-established relationships with national buyers and retailers (A)",
        "Technology Use": "High; utilizes modern e-commerce platforms and digital payment systems (A)",
        "GST Data": "Excellent; consistent sales and purchase records with full compliance (A)",
        "Financial Health": "Strong; robust revenue with diversified trading partnerships (A)",
        "Risk Factors": "Low market risk due to high demand for non-perishable goods (B)"
      },
      "Overall Rating": "A",
      "Recommendation": "Sunita Reddy is eligible for a loan. Suggested investments in expanding inventory and enhancing digital marketing strategies to increase market reach and revenue."

    },
}
    
    //   id: 8,
    //   name: "Sanjay",
    //   state: "Rajasthan",
    //   "Amount Required": 85000,
    //   "Annual Revenue": 1300000,
    //   amountReceived: 80000,
    //   "PRIMARY GOODS TRADED": "Barley, Pulses",
    //   EXPERIENCE: "2-5 years",
    //   "CREDIT SCORE": "660 (B-)",
    //   "MARKET ACCESS": "Average; moderate connections in local market",
    //   "TECHNOLOGY USE": "Basic; limited use of digital platforms",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements some sustainable farming methods",
    //   "FINANCIAL HEALTH": "Stable; consistent revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹85,000",
    //   REPAYMENT_STRUCTURE: "Quarterly installments over 3 years with adjustments during peak seasons",
    //   "Overall Rating": "B-",
    //   Recommendation: "Sanjay qualifies for an ₹85,000 loan with a repayment plan designed to accommodate seasonal variations. Further investment in technology and sustainable practices could enhance profitability and reduce risk.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": true,
    //   "Livestock Products": false,
    //   "Small (< 50 Lakhs)": true,
    //   "Medium ( 50 Lakhs - 1 Crore)": false,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": false,
    //   Traditional: true,
    //   "Less than ₹50,00,000": true,
    //   "More than ₹50,00,000": false,
    //   "Less than ₹1,00,000": true,
    //   "More than ₹1,00,000": false,
    // },
    // {
    //   id: 9,
    //   name: "Smita",
    //   state: "Gujarat",
    //   "Amount Required": 95000,
    //   "Annual Revenue": 1400000,
    //   amountReceived: 90000,
    //   "PRIMARY GOODS TRADED": "Cotton, Groundnuts",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "720 (A)",
    //   "MARKET ACCESS": "Excellent; well-established network with strong market presence",
    //   "TECHNOLOGY USE": "Advanced; utilizes digital platforms for trading and sales",
    //   "SUSTAINABILITY PRACTICES": "High; actively implements sustainable farming methods",
    //   "FINANCIAL HEALTH": "Robust; consistent growth in revenue and profitability",
    //   "RISK FACTORS": "Low; diversified income sources and stable market demand",
    //   "LOAN AMOUNT RECOMMENDED": "₹95,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A",
    //   Recommendation: "Smita qualifies for a ₹95,000 loan with flexible repayment options. With strong market access and advanced technology use, she has the potential for significant growth and expansion.",
    //   "North India": false,
    //   "South India": false,
    //   "East India": false,
    //   "West India": true,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": true,
    //   "Perishable Goods": false,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },
    // {
    //   id: 10,
    //   name: "Amit",
    //   state: "Bihar",
    //   "Amount Required": 105000,
    //   "Annual Revenue": 1500000,
    //   amountReceived: 100000,
    //   "PRIMARY GOODS TRADED": "Rice, Wheat",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "710 (A-)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹1,05,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A-",
    //   Recommendation: "Amit qualifies for a ₹1,05,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": false,
    //   "South India": false,
    //   "East India": true,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": true,
    //   "Perishable Goods": false,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },{
    //   id: 11,
    //   name: "Rajesh",
    //   state: "Uttarakhand",
    //   "Amount Required": 95000,
    //   "Annual Revenue": 1400000,
    //   amountReceived: 90000,
    //   "PRIMARY GOODS TRADED": "Apples, Grapes",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "720 (A)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹95,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A",
    //   Recommendation: "Rajesh qualifies for a ₹95,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },
    // {
    //   id: 12,
    //   name: "Priya",
    //   state: "Maharashtra",
    //   "Amount Required": 105000,
    //   "Annual Revenue": 1500000,
    //   amountReceived: 100000,
    //   "PRIMARY GOODS TRADED": "Mangoes, Oranges",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "710 (A-)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹1,05,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A-",
    //   Recommendation: "Priya qualifies for a ₹1,05,000 loan with flexible repayment options. With established local market connections and moderate technology use, she has the potential for growth and expansion.",
    //   "North India": false,
    //   "South India": true,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },{
    //   id: 14,
    //   name: "Vijay",
    //   state: "Madhya Pradesh",
    //   "Amount Required": 90000,
    //   "Annual Revenue": 1350000,
    //   amountReceived: 85000,
    //   "PRIMARY GOODS TRADED": "Wheat, Soybeans",
    //   EXPERIENCE: "2-5 years",
    //   "CREDIT SCORE": "670 (B-)",
    //   "MARKET ACCESS": "Average; moderate connections in local market",
    //   "TECHNOLOGY USE": "Basic; limited use of digital platforms",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹90,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "B-",
    //   Recommendation: "Vijay qualifies for a ₹90,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": false,
    //   Traditional: true,
    //   "Less than ₹50,00,000": true,
    //   "More than ₹50,00,000": false,
    //   "Less than ₹1,00,000": true,
    //   "More than ₹1,00,000": false,
    // },
    // {
    //   id: 15,
    //   name: "Deepak",
    //   state: "Uttar Pradesh",
    //   "Amount Required": 95000,
    //   "Annual Revenue": 1400000,
    //   amountReceived: 90000,
    //   "PRIMARY GOODS TRADED": "Rice, Maize",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "710 (A-)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹95,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A-",
    //   Recommendation: "Deepak qualifies for a ₹95,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },{
    //   id: 17,
    //   name: "Neha",
    //   state: "Rajasthan",
    //   "Amount Required": 95000,
    //   "Annual Revenue": 1400000,
    //   amountReceived: 90000,
    //   "PRIMARY GOODS TRADED": "Mustard, Guar",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "710 (A-)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹95,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A-",
    //   Recommendation: "Neha qualifies for a ₹95,000 loan with flexible repayment options. With established local market connections and moderate technology use, she has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },
    // {
    //   id: 18,
    //   name: "Manish",
    //   state: "Bihar",
    //   "Amount Required": 100000,
    //   "Annual Revenue": 1450000,
    //   amountReceived: 95000,
    //   "PRIMARY GOODS TRADED": "Rice, Wheat",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "700 (B+)",
    //   "MARKET ACCESS": "Average; moderate connections in local market",
    //   "TECHNOLOGY USE": "Basic; limited use of digital platforms",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹1,00,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "B+",
    //   Recommendation: "Manish qualifies for a ₹1,00,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": false,
    //   Traditional: true,
    //   "Less than ₹50,00,000": true,
    //   "More than ₹50,00,000": false,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },{  id: 19,
    //   name: "Rahul",
    //   state: "Uttarakhand",
    //   "Amount Required": 98000,
    //   "Annual Revenue": 1500000,
    //   amountReceived: 92000,
    //   "PRIMARY GOODS TRADED": "Apples, Grapes",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "720 (A)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹98,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A",
    //   Recommendation: "Rahul qualifies for a ₹98,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },
    // {
    //   id: 20,
    //   name: "Amit",
    //   state: "Haryana",
    //   "Amount Required": 96000,
    //   "Annual Revenue": 1450000,
    //   amountReceived: 91000,
    //   "PRIMARY GOODS TRADED": "Tomatoes, Potatoes",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "710 (A-)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹96,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A-",
    //   Recommendation: "Amit qualifies for a ₹96,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },
    // {
    //   id: 21,
    //   name: "Rajesh",
    //   state: "Gujarat",
    //   "Amount Required": 97000,
    //   "Annual Revenue": 1480000,
    //   amountReceived: 93000,
    //   "PRIMARY GOODS TRADED": "Groundnuts, Sesame",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "715 (A-)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹97,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A-",
    //   Recommendation: "Rajesh qualifies for a ₹97,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": false,
    //   "South India": false,
    //   "East India": false,
    //   "West India": true,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },  {
    //   id: 16,
    //   name: "Vikram",
    //   state: "Madhya Pradesh",
    //   "Amount Required": 99000,
    //   "Annual Revenue": 1520000,
    //   amountReceived: 94000,
    //   "PRIMARY GOODS TRADED": "Soybeans, Wheat",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "725 (A+)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹99,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A+",
    //   Recommendation: "Vikram qualifies for a ₹99,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },
    // {
    //   id: 13,
    //   name: "Rajat",
    //   state: "Uttar Pradesh",
    //   "Amount Required": 97000,
    //   "Annual Revenue": 1470000,
    //   amountReceived: 91000,
    //   "PRIMARY GOODS TRADED": "Potatoes, Onions",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "710 (A-)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹97,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A-",
    //   Recommendation: "Rajat qualifies for a ₹97,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": true,
    //   "South India": false,
    //   "East India": false,
    //   "West India": false,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // },
    // {
    //   id: 7,
    //   name: "Prakash",
    //   state: "Maharashtra",
    //   "Amount Required": 96000,
    //   "Annual Revenue": 1460000,
    //   amountReceived: 92000,
    //   "PRIMARY GOODS TRADED": "Mangoes, Grapes",
    //   EXPERIENCE: "More than 5 years",
    //   "CREDIT SCORE": "715 (A-)",
    //   "MARKET ACCESS": "Good; established local market connections",
    //   "TECHNOLOGY USE": "Moderate; uses digital platforms for some aspects of trading",
    //   "SUSTAINABILITY PRACTICES": "Intermediate; implements sustainable practices to some extent",
    //   "FINANCIAL HEALTH": "Stable; steady revenue with potential for growth",
    //   "RISK FACTORS": "Moderate; influenced by seasonal market fluctuations",
    //   "LOAN AMOUNT RECOMMENDED": "₹96,000",
    //   REPAYMENT_STRUCTURE: "Monthly installments over 4 years with flexible options for early repayment",
    //   "Overall Rating": "A-",
    //   Recommendation: "Prakash qualifies for a ₹96,000 loan with flexible repayment options. With established local market connections and moderate technology use, he has the potential for growth and expansion.",
    //   "North India": false,
    //   "South India": false,
    //   "East India": false,
    //   "West India": true,
    //   "Agricultural Products": false,
    //   "Livestock Products": true,
    //   "Small (< 50 Lakhs)": false,
    //   "Medium ( 50 Lakhs - 1 Crore)": true,
    //   "Non-Perishable Goods": false,
    //   "Perishable Goods": true,
    //   "Modern (E-commerce, ONDC Platform, Digital Payments)": true,
    //   Traditional: false,
    //   "Less than ₹50,00,000": false,
    //   "More than ₹50,00,000": true,
    //   "Less than ₹1,00,000": false,
    //   "More than ₹1,00,000": true,
    // }
  ]